apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  versions:
  - schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              controllerNamespace:
                description: ControllerNamespace indicates the namespace in which
                  the application controller is located
                type: string
              operationState:
                properties:
                  syncResult:
                    properties:
                      managedNamespaceMetadata:
                        description: ManagedNamespaceMetadata contains the current
                          sync state of managed namespace metadata
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            type: object
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
